### ISSUE TITLE
Get /<table name>/<id> not working

### ISSUE THREAD

**Issue by damies13** [damies13/TestDataTable#6]
On Thu, 6 Feb 2020 at 03:43, Simon Benson <simonbenson14@g.....com> wrote:
...
I'm validating using Robot Framework and everything seems to work fine except when I try to use the operation "/\<table name\>/\<id\>" which is documented in your API Documentation but upon further investigation I don't see any tests in your regression testing for this to use as example.

This is the table  
![image](https://user-images.githubusercontent.com/15232871/73927983-1ba70a80-491e-11ea-8ca5-cc06d2a986d3.png)

and here is the operation failing 
![image (1)](https://user-images.githubusercontent.com/15232871/73928066-38434280-491e-11ea-8dc9-ba88cec4c712.png)

and here is the "row" operation succeeding  
![unnamed](https://user-images.githubusercontent.com/15232871/73928125-4db86c80-491e-11ea-9ab8-1d72a80c2475.png)

**Comment by damies13** [comment]
v0.2.1 resolves this issue

**Comment by simonbenson14** [comment]
Issue #6 It now works but pulls an unexpected row.
When sending the operation "http://desktop-k8g2q8n/TestData/3" I get row 4.
Is this because it's zero based though the row numbers are not?
See attached.
![image](https://user-images.githubusercontent.com/52324828/74034306-ecd97480-49af-11ea-91df-1e8134c17e82.png)
![image](https://user-images.githubusercontent.com/52324828/74034323-f4991900-49af-11ea-836b-e0cc515c122e.png)

**Comment by damies13** [comment]
I actually wondered what I should do there, when you request "http://desktop-k8g2q8n/TestData/3" yes you are requesting the 4th row, because the row id's start from zero. I was wondering of the row numbers displayed should also start from zero?

Hopefully this screen shot will make things clearer:
<img width="451" alt="Screen Shot 2020-02-09 at 10 42 18 am" src="https://user-images.githubusercontent.com/15232871/74094221-63e64880-4b29-11ea-9790-4e3bb4332263.png">
